version: "3.8"
services:
  grafana:
    restart: unless-stopped
    image: marcinbojko/grafana-custom:10.2.4.20240304
    ports:
     - "3000:3000"
    volumes:
      - grafana_lib:/var/lib/grafana
      - grafana_log:/var/log/grafana
      - grafana_etc:/etc/grafana
    environment:
      GF_RENDERING_SERVER_URL: http://renderer:8081/render
      GF_RENDERING_CALLBACK_URL: http://grafana:3000/
      GF_LOG_FILTERS: rendering:debug
      GF_PLUGINS_ALLOW_LOADING_UNSIGNED_PLUGINS: grafana-image-renderer,victoriametrics-datasource
  renderer:
    image: grafana/grafana-image-renderer:latest
    ports:
      - 8081
    environment:
      ENABLE_METRICS: 'true'
volumes:
  grafana_lib: {}
  grafana_log: {}
  grafana_etc: {}

